# Generated by Django 5.2.1 on 2025-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_crop_equipment_livestock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("unit", models.CharField(max_length=100)),
            ],
        ),
    ]
