# Generated by Django 5.2.1 on 2025-06-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_crop_id_alter_equipment_id_alter_livestock_id_and_more"),
        ("app", "0003_supplies"),
    ]

    operations = []
