# Generated by Django 4.2.23 on 2025-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_crop_id_alter_equipment_id_alter_livestock_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("Crop", "Crop"), ("Supply", "Supply")], max_length=20
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Sale", "Sale"), ("Purchase", "Purchase")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
