# Generated by Django 4.2.23 on 2025-06-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("Crop", "Crop"),
                    ("Livestock", "Livestock"),
                    ("Equipment", "Equipment"),
                    ("Supplies", "Supplies"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Sale", "Sale"),
                    ("Purchase", "Purchase"),
                    ("Return", "Return"),
                ],
                max_length=20,
            ),
        ),
    ]
