name: CI

on:
  push:
    branches: [ Prod ]
  pull_request:
    branches: [ Prod ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'

      - name: Install dependencies
        run: make build

      - name: Run tests
        run: make test